repository: panga/panga.github.io
favicon: images/favicon.ico
darkmode: never

name: Leonardo Zanivan
title: Software Architect
email: leonardo.zanivan@gmail.com
phone: +55 48996186781
#blog: medium.com/@leonardopanga
github_username:  panga
linkedin_username: leonardozanivan
#slideshare_username: leonardozanivan

about_title: Summary
about_profile_image: images/profile.jpg
about_content: |
  - Hands-on software architect specialized on high scalability.
  - Quick learner with strong problem-solving skills.
  - Speaker in software developer events such as QCon, JavaOne, and The Developers Conference.
  - Open Source enthusiast and contributor such as DuckDB, Hibernate, Spring, Keycloak.

  The technologies I am most skilled in: <mark>Java</mark>, <mark>Node.js</mark>, <mark>Go</mark>, <mark>Python</mark>, <mark>PostgreSQL</mark>, <mark>MongoDB</mark>, <mark>MySQL</mark>, <mark>Cassandra</mark>, <mark>DynamoDB</mark>, <mark>Redis</mark>, <mark>Kafka</mark>, <mark>ElasticSearch</mark>, <mark>OpenTelemetry</mark>, <mark>DataDog</mark>, <mark>Terraform</mark>, <mark>Docker</mark>, <mark>Kubernetes</mark>, <mark>AWS</mark>, <mark>Azure</mark>.

experience_title: Work Experience

educaton_title: Education

projects_title: Projects

footer_show_references: false

remote_theme: panga/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag